keys:
  - &cluster age1f09any8ydtdgumr6vs0zd55z6xq4z6mtph2fs02f65kmx7t6y3ssvt5yh3
creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - pgp:
          - "EB3CD1265EB311BEFE3B3F25CE305C8F378F80D8"
        age:
          - *cluster
