name: update-flake-lock
on:
  workflow_dispatch:
  schedule:
    - cron: "30 2 * * *"

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install Determinate Nix
        uses: DeterminateSystems/determinate-nix-action@v3
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          token: ${{ secrets.GH_UPDATE_TOKEN }}
          pr-title: "Update Nix flake inputs"
          pr-assignees: dvprokofiev
          pr-labels: |
            dependencies
            automated
